-- =============================================================================
-- Self-healing occurrence generation: prune stale pending rows.
--
-- Occurrences are generated by TWO paths that deploy independently:
--   1. this SQL function (fired by the AFTER INSERT/UPDATE trigger on
--      recurring_transaction_templates_enc), applied via `supabase db push`
--   2. ensureOccurrencesForRange() in the webapp, deployed via Docker
--
-- The 20260702 quincenal fix changed BOTH from "every 14 days" to
-- month-anchored day pairs — but during the deploy skew where one side runs
-- the old logic and the other the new, each inserts its own date for the same
-- quincena (e.g. Jul 29 from 14-day steps AND Jul 30 from the anchored pair).
-- Everything inserts with ON CONFLICT DO NOTHING and nothing ever deleted the
-- drifted row, so users saw duplicate upcoming payments on consecutive days.
--
-- Fix: after computing the template's schedule for the generation range,
-- DELETE pending, unlinked occurrences inside that range whose date the
-- schedule does not produce. The webapp side gets the same pruning in
-- ensureOccurrencesForRange() — either path now heals the other's leftovers.
--
-- MONTHLY is excluded on purpose: the webapp keeps exactly one occurrence per
-- month whose day may legitimately drift when a statement import updates the
-- due day; pruning by exact date would fight that.
--
-- Also runs a one-time regeneration over every active template so existing
-- drifted rows (the Jul 29/30 duplicates) are cleaned immediately on push.
-- =============================================================================

CREATE OR REPLACE FUNCTION generate_occurrences_for_template(p_template_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id       uuid;
  v_amount        numeric(15,2);
  v_start_date    date;
  v_end_date      date;
  v_frequency     text;
  v_is_active     boolean;
  v_range_start   date;
  v_range_end     date;
  v_cursor        date;
  v_step          integer;
  v_dates         date[] := '{}';
BEGIN
  SELECT user_id, amount, start_date, end_date, frequency::text, is_active
    INTO v_user_id, v_amount, v_start_date, v_end_date, v_frequency, v_is_active
  FROM recurring_transaction_templates_enc
  WHERE id = p_template_id;

  IF NOT FOUND THEN RETURN; END IF;
  IF NOT v_is_active THEN RETURN; END IF;

  -- Colombia-local "today": plain now() is UTC, which rolls the month over at
  -- ~7pm COT on the last day of the month and would generate the wrong range.
  v_range_start := date_trunc('month', now() AT TIME ZONE 'America/Bogota')::date;
  v_range_end   := (date_trunc('month', now() AT TIME ZONE 'America/Bogota')
                     + interval '1 month'
                     - interval '1 day'
                     + interval '14 days')::date;

  IF v_frequency = 'ONCE' THEN
    IF v_start_date BETWEEN v_range_start AND v_range_end
       AND (v_end_date IS NULL OR v_start_date <= v_end_date) THEN
      v_dates := array_append(v_dates, v_start_date);
      INSERT INTO recurring_occurrences
        (template_id, user_id, occurrence_date, expected_amount, status)
      VALUES
        (p_template_id, v_user_id, v_start_date, v_amount, 'pending')
      ON CONFLICT (template_id, occurrence_date) DO NOTHING;
    END IF;

    -- Prune pending unlinked rows the (possibly edited) start_date no longer
    -- covers. `<> ALL('{}')` is vacuously true, so an out-of-range/ended ONCE
    -- template gets all its stale pending rows in the window removed.
    DELETE FROM recurring_occurrences
    WHERE template_id = p_template_id
      AND status = 'pending'
      AND transaction_id IS NULL
      AND occurrence_date BETWEEN v_range_start AND v_range_end
      AND occurrence_date <> ALL(v_dates);
    RETURN;
  END IF;

  -- Single loop over every step from anchor; insert only when the cursor
  -- falls inside [range_start, range_end]. Keeps the frequency CASE in one
  -- place (vs. a duplicated advance-then-collect pattern).
  v_step := 0;
  v_cursor := v_start_date;

  WHILE v_cursor <= v_range_end LOOP
    IF v_end_date IS NOT NULL AND v_cursor > v_end_date THEN EXIT; END IF;

    IF v_cursor >= v_range_start THEN
      v_dates := array_append(v_dates, v_cursor);
      INSERT INTO recurring_occurrences
        (template_id, user_id, occurrence_date, expected_amount, status)
      VALUES
        (p_template_id, v_user_id, v_cursor, v_amount, 'pending')
      ON CONFLICT (template_id, occurrence_date) DO NOTHING;
    END IF;

    v_step := v_step + 1;
    v_cursor := CASE v_frequency
      WHEN 'WEEKLY'    THEN (v_start_date + (v_step * interval '7 days'))::date
      WHEN 'BIWEEKLY'  THEN quincenal_occurrence_at(v_start_date, v_step)
      WHEN 'MONTHLY'   THEN (v_start_date + (v_step * interval '1 month'))::date
      WHEN 'QUARTERLY' THEN (v_start_date + (v_step * interval '3 months'))::date
      WHEN 'ANNUAL'    THEN (v_start_date + (v_step * interval '1 year'))::date
      ELSE NULL
    END;
    IF v_cursor IS NULL THEN EXIT; END IF;
  END LOOP;

  -- Prune stale pending unlinked rows inside the generated range: dates the
  -- current schedule does not produce (drifted quincenas, pre-edit dates).
  -- MONTHLY keeps its one-per-month row even when the day drifted.
  IF v_frequency <> 'MONTHLY' THEN
    DELETE FROM recurring_occurrences
    WHERE template_id = p_template_id
      AND status = 'pending'
      AND transaction_id IS NULL
      AND occurrence_date BETWEEN v_range_start AND v_range_end
      AND occurrence_date <> ALL(v_dates);
  END IF;
END;
$$;

-- ── One-time heal: regenerate (and thereby prune) every active template ──────
-- Fixes already-materialized duplicates like the Jul 29/30 quincenal pair.
-- Paid/skipped history and anything linked to a transaction is untouched.
DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN
    SELECT id FROM recurring_transaction_templates_enc
    WHERE is_active
  LOOP
    PERFORM generate_occurrences_for_template(t.id);
  END LOOP;
END $$;
